<a href="https://colab.research.google.com/github/2303A51531/23CSBTB39-40/blob/main/sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Creating a 1D array
array1 = np.array([1, 2, 3, 4, 5])

# Creating a 2D array (matrix)
array2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D array:")
print(array1)

print("\n2D array:")
print(array2)


1D array:
[1 2 3 4 5]

2D array:
[[1 2 3]
 [4 5 6]]
